name: Sync to Pi 3B+ (HUB75 Panel)

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Sync code to Pi 3B+
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PI_3B_HOST }}
        username: ${{ secrets.PI_3B_USER }}
        key: ${{ secrets.PI_3B_SSH_KEY }}
        port: ${{ secrets.PI_3B_PORT }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p ~/LightBox_2.0
          cd ~/LightBox_2.0
          
          # If git repo exists, pull updates
          if [ -d .git ]; then
            echo "Updating existing repository..."
            git pull origin main
          else
            # Clone fresh if not exists
            echo "Cloning repository..."
            cd ~
            git clone https://github.com/fieldjoshua/LightBox_2.0.git
            cd ~/LightBox_2.0
          fi
          
          # Install/update dependencies
          echo "Updating dependencies..."
          pip3 install -r requirements-optimized.txt
          
          # Install HUB75 library if not present
          if ! python3 -c "import rgbmatrix" 2>/dev/null; then
            echo "Installing RGB Matrix library..."
            sudo bash scripts/install_rgb_matrix.sh
          fi
          
          echo "Sync complete! Code is up to date."
          echo "Platform: Pi 3B+ with HUB75 support"
          echo "To run: cd ~/LightBox_2.0 && sudo python3 lightbox.py"